<?php
/**
 * BookRec Email Service
 * 
 * Handles sending book recommendations as PDF via email
 * 
 * @package GoodEReader\BookRec
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Class BookRec_Email_Service
 * 
 * Handles the generation and delivery of book recommendations as PDF via email
 */
class BookRec_Email_Service {
    /**
     * Constructor
     */
    public function __construct() {
        // Check if mPDF is available before any operations
        if (!class_exists('\Mpdf\Mpdf')) {
            error_log('BookRec: mPDF library not found. PDF generation features will not work.');
        }
    }
    
    /**
     * Send recommendations as PDF attachment via email
     * 
     * @param string $recipient_email The email address to send recommendations to
     * @param array $recommendations Array of book recommendation data
     * @param string $user_query The user's original query that resulted in these recommendations
     * @return bool True if email was sent successfully, false otherwise
     */
    public function sendRecommendationsAsPDF(string $recipient_email, array $recommendations, string $user_query): bool {
        // Validate email
        if (!is_email($recipient_email)) {
            error_log("BookRec: Invalid email address provided: {$recipient_email}");
            return false;
        }
        
        // Check if we have any recommendations
        if (empty($recommendations) || !is_array($recommendations)) {
            error_log("BookRec: No valid recommendations provided for PDF generation");
            return false;
        }
        
        try {
            // Generate HTML content for the PDF
            $html_content = $this->generateHtmlContent($recommendations, $user_query);
            
            // Initialize mPDF
            $mpdf = new \Mpdf\Mpdf([
                'mode' => 'utf-8',
                'format' => 'A4',
                'margin_left' => 15,
                'margin_right' => 15,
                'margin_top' => 16,
                'margin_bottom' => 16,
                'margin_header' => 9,
                'margin_footer' => 9,
            ]);
            
            // Set document information
            $mpdf->SetTitle('Book Recommendations from Good E-Reader');
            $mpdf->SetAuthor('Good E-Reader');
            $mpdf->SetCreator('Good E-Reader BookRec');
            
            // Add custom header with logo if available
            $mpdf->SetHTMLHeader('<div style="text-align: right; font-weight: bold; font-size: 10pt;">Good E-Reader Book Recommendations</div>');
            
            // Add footer with page numbers
            $mpdf->SetHTMLFooter('<div style="text-align: center; font-size: 8pt;">Page {PAGENO} of {nbpg} | Generated by Good E-Reader BookRec</div>');
            
            // Write content to PDF
            $mpdf->WriteHTML($html_content);
            
            // Generate PDF content as string
            $pdf_content = $mpdf->Output('', 'S'); // 'S' returns as string
            
            // Create temporary file for the attachment
            $upload_dir = wp_upload_dir();
            $temp_dir = $upload_dir['basedir'] . '/bookrec-temp';
            
            // Create temp directory if it doesn't exist
            if (!file_exists($temp_dir)) {
                wp_mkdir_p($temp_dir);
                
                // Add .htaccess to prevent direct access
                $htaccess_content = "Order deny,allow\nDeny from all";
                file_put_contents($temp_dir . '/.htaccess', $htaccess_content);
            }
            
            // Create unique filename
            $temp_filename = $temp_dir . '/bookrec_' . md5(time() . rand()) . '.pdf';
            file_put_contents($temp_filename, $pdf_content);
            
            // Prepare email content
            $to = $recipient_email;
            $subject = sprintf(
                /* translators: %s: Site name */
                __('Your Book Recommendations from %s', 'goodereader-bookrec'),
                get_bloginfo('name')
            );
            
            // Email body HTML
            $body = '<!DOCTYPE html>
            <html>
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <title>' . esc_html($subject) . '</title>
            </head>
            <body style="margin: 0; padding: 0; font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="text-align: center; margin-bottom: 20px;">
                        <h1 style="color: #000; margin: 0;">' . esc_html__('Your Book Recommendations', 'goodereader-bookrec') . '</h1>
                    </div>
                    
                    <div style="background-color: #f8f8f8; border: 1px solid #e5e5e5; border-radius: 5px; padding: 20px; margin-bottom: 20px;">
                        <p>' . sprintf(
                            /* translators: %s: User search query */
                            esc_html__('Here are the book recommendations you requested based on "%s".', 'goodereader-bookrec'),
                            esc_html($user_query)
                        ) . '</p>
                        
                        <p>' . esc_html__('We\'ve attached a PDF file containing the full recommendations, complete with book covers and descriptions.', 'goodereader-bookrec') . '</p>
                        
                        <p>' . esc_html__('You can save this PDF for future reference or print it to take with you to your local bookstore.', 'goodereader-bookrec') . '</p>
                    </div>
                    
                    <div style="border-top: 1px solid #e5e5e5; padding-top: 20px; color: #777; font-size: 12px;">
                        <p>' . sprintf(
                            /* translators: %s: Site name */
                            esc_html__('This email was sent from %s using the Book Recommendation feature.', 'goodereader-bookrec'),
                            '<a href="' . esc_url(home_url()) . '" style="color: #555;">' . esc_html(get_bloginfo('name')) . '</a>'
                        ) . '</p>
                    </div>
                </div>
            </body>
            </html>';
            
            // Set headers to send HTML email
            $headers = [
                'Content-Type: text/html; charset=UTF-8',
                'From: ' . get_bloginfo('name') . ' <' . get_option('admin_email') . '>'
            ];
            
            // Set attachment
            $attachments = [$temp_filename];
            
            // Send email
            $email_sent = wp_mail($to, $subject, $body, $headers, $attachments);
            
            // Clean up temporary file
            @unlink($temp_filename);
            
            // Log success or failure
            if ($email_sent) {
                error_log("BookRec: Successfully sent book recommendations PDF to {$recipient_email}");
                return true;
            } else {
                error_log("BookRec: Failed to send book recommendations PDF to {$recipient_email}");
                return false;
            }
            
        } catch (\Exception $e) {
            error_log("BookRec: Error generating or sending PDF: " . $e->getMessage());
            return false;
        }
    }
    
    /**
     * Generate HTML content for the PDF
     * 
     * @param array $recommendations Array of book recommendation data
     * @param string $user_query The user's original query
     * @return string HTML content for the PDF
     */
    private function generateHtmlContent(array $recommendations, string $user_query): string {
        // Start HTML content
        $html = '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Your Book Recommendations</title>
            <style>
                body {
                    font-family: Arial, Helvetica, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    margin: 0;
                    padding: 0;
                }
                .container {
                    width: 100%;
                    margin: 0 auto;
                }
                .header {
                    text-align: center;
                    margin-bottom: 20px;
                    padding-bottom: 10px;
                    border-bottom: 1px solid #ccc;
                }
                .header h1 {
                    font-size: 24px;
                    margin-bottom: 5px;
                }
                .header p {
                    color: #666;
                    font-size: 14px;
                    margin-top: 0;
                }
                .book {
                    margin-bottom: 30px;
                    page-break-inside: avoid;
                    clear: both;
                    overflow: hidden;
                    border-bottom: 1px solid #eee;
                    padding-bottom: 20px;
                }
                .book:last-child {
                    border-bottom: none;
                }
                .book-cover {
                    float: left;
                    width: 20%;
                    max-width: 120px;
                    margin-right: 20px;
                }
                .book-cover img {
                    max-width: 100%;
                    height: auto;
                    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
                }
                .book-details {
                    float: left;
                    width: 70%;
                }
                .book-title {
                    font-size: 18px;
                    font-weight: bold;
                    margin: 0 0 5px 0;
                }
                .book-author {
                    font-size: 16px;
                    color: #555;
                    margin: 0 0 10px 0;
                }
                .book-description {
                    font-size: 14px;
                }
                .book-metadata {
                    font-size: 12px;
                    color: #777;
                    margin-top: 10px;
                }
                .book-link {
                    color: #000;
                    text-decoration: none;
                    font-weight: bold;
                }
                .footer {
                    text-align: center;
                    font-size: 12px;
                    color: #777;
                    margin-top: 30px;
                    padding-top: 10px;
                    border-top: 1px solid #eee;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Your Book Recommendations</h1>';
        
        // Add query if provided
        if (!empty($user_query)) {
            $html .= '<p>Based on your interest in: "' . esc_html($user_query) . '"</p>';
        }
        
        $html .= '</div>
                
                <div class="recommendations">';
        
        // Add each book recommendation
        foreach ($recommendations as $book) {
            $html .= '<div class="book">';
            
            // Book cover (if available)
            $html .= '<div class="book-cover">';
            if (!empty($book['coverUrl'])) {
                $html .= '<img src="' . esc_url($book['coverUrl']) . '" alt="Cover of ' . esc_attr($book['title']) . '">';
            } else {
                $html .= '<div style="height: 150px; background-color: #f0f0f0; text-align: center; line-height: 150px; font-size: 12px;">No Cover Available</div>';
            }
            $html .= '</div>';
            
            // Book details
            $html .= '<div class="book-details">';
            $html .= '<h2 class="book-title">' . esc_html($book['title']) . '</h2>';
            $html .= '<h3 class="book-author">by ' . esc_html($book['author']) . '</h3>';
            
            // Book description
            if (!empty($book['description'])) {
                $html .= '<div class="book-description">' . esc_html($book['description']) . '</div>';
            }
            
            // Book metadata
            $html .= '<div class="book-metadata">';
            
            if (!empty($book['publishDate'])) {
                $html .= '<span>Published: ' . esc_html($book['publishDate']) . '</span> | ';
            }
            
            if (!empty($book['publisher'])) {
                $html .= '<span>Publisher: ' . esc_html($book['publisher']) . '</span> | ';
            }
            
            if (!empty($book['isbn'])) {
                $html .= '<span>ISBN: ' . esc_html($book['isbn']) . '</span>';
            }
            
            $html .= '</div>';
            
            // Amazon link (as text in PDF)
            if (!empty($book['amazonLink'])) {
                $html .= '<div style="margin-top: 15px;">';
                $html .= '<p>Find this book on Amazon: ' . esc_url($book['amazonLink']) . '</p>';
                $html .= '</div>';
            }
            
            $html .= '</div>'; // End book-details
            $html .= '</div>'; // End book
        }
        
        $html .= '</div>'; // End recommendations
        
        // Footer
        $html .= '<div class="footer">
                <p>Generated by Good E-Reader BookRec on ' . date('F j, Y') . '</p>
                <p>' . esc_url(home_url()) . '</p>
            </div>
            </div>
        </body>
        </html>';
        
        return $html;
    }
}